# Generated by Django 4.2.2 on 2023-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Укажите адрес', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/shop_01-01.jpg', upload_to='profile_img/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Укажите номер телефона', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
