# Generated by Django 4.2.2 on 2023-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_colorchoices_alter_product_size_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/', verbose_name='Фото профиля'),
        ),
    ]
